handlebars:
  suffix: .html
server:
  compression:
    enabled: true
    min-response-size: 10
#server:
#  tomcat:
#    accept-count: 1
#    max-connections: 1
#    threads:
#      max: 2
#spring:
#  mvc:
#    view:
#      suffix: .html
#  thymeleaf:
#    suffix: .html
